# AIM logger configuration

aim:
  _target_: aim.pytorch_lightning.AimLogger
  experiment: ${logger.aim.experiment}
  train_metric_prefix: "train/"
  test_metric_prefix: "test/"
  val_metric_prefix: "val/"
